#pragma once
// FFI adapter — the boundary described in ADR-3.
//
// This deliberately does NOT touch OrderBookV2 itself (already fuzz-tested
// against v1 and clean under ThreadSanitizer/AddressSanitizer — see ADR-2 and
// the devlog). It only translates between cxx's generated mirror types
// (FfiOrderRequest, FfiTrade, FfiSide, FfiOrderType — declared in
// rust/src/ffi.rs) and the real ::OrderRequest / ::Trade / ::Side / ::Type
// used everywhere else in cpp/. If this file has a bug, the matching logic
// underneath is still provably correct; only the translation layer is new
// and unverified.
//
// Included from two places:
//   1. cpp/src/order_book_v2_ffi.cpp (the implementation)
//   2. rust/build.rs, via cxx_build's generated bridge, when compiling the
//      Rust sidecar — see rust/src/ffi.rs's `include!(...)`.
//
// NOTE: matching-engine-sidecar/src/ffi.rs.h is generated by cxx_build at
// Rust-build time (from rust/src/ffi.rs) — it does not exist until `cargo
// build` has been run at least once from rust/. This header will not compile
// standalone before that.

#include "order_book_v2.h"
#include "matching-engine-sidecar/src/ffi.rs.h"
#include "rust/cxx.h"

#include <cstdint>
#include <memory>

class OrderBookV2Ffi {
public:
    OrderBookV2Ffi(uint32_t arena_capacity, int64_t initial_window);

    rust::Vec<FfiTrade> add(FfiOrderRequest req);
    bool cancel(uint64_t id);
    bool reduce(uint64_t id, uint64_t delta);

    int64_t best_bid() const;
    int64_t best_ask() const;
    bool    has_bid() const;
    bool    has_ask() const;
    size_t  depth() const;

private:
    OrderBookV2 inner_;
};

// Factory — cxx doesn't support constructors directly, so Rust calls this
// free function to get a UniquePtr<OrderBookV2Ffi>. See rust/src/ffi.rs.
std::unique_ptr<OrderBookV2Ffi> make_order_book(uint32_t arena_capacity, int64_t initial_window);
